name: 🚀 CI - Build, Lint, and Test

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    name: 🔧 CI Job (Node.js)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Adjust as needed

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧹 Lint code
        run: npm run lint

      - name: 🧪 Run tests
        run: npm run test

      # Optional: TypeScript check
      - name: 🧠 Type check (optional)
        if: exists('tsconfig.json')
        run: npm run typecheck

      # Optional: Build check
      - name: 🏗️ Build project
        run: npm run build
