name: 💤 Mark stale issues and PRs

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2:00 AM UTC

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          # ❗️Time thresholds
          days-before-stale: 30
          days-before-close: 7

          # 🏷️ Labels
          stale-issue-label: "stale"
          stale-pr-label: "stale"

          # 💬 Messages
          stale-issue-message: >
            This issue has been automatically marked as stale due to 30 days of inactivity.
            It will be closed in 7 days if no further updates are made.
            If this is still relevant, feel free to comment or update the issue.

          stale-pr-message: >
            This pull request has been marked as stale due to 30 days of inactivity.
            It will be closed in 7 days if no further activity occurs.

          close-issue-message: >
            This issue was closed due to inactivity. Please reopen if needed.

          close-pr-message: >
            This PR was closed due to inactivity. Feel free to reopen if it’s still relevant.

          # 🔧 Filters
          exempt-issue-labels: "pinned, security, keep-open"
          exempt-pr-labels: "work-in-progress, keep-open"
          exempt-draft-pr: true
